#index:
#    path: /
#    controller: App\Controller\DefaultController::index
destination_new:
    path: /destination/new
    controller: App\Controller\DestinationController::new

course_new:
    path: /course/new
    controller: App\Controller\CourseController::new

course_edit:
    path: /course/edit
    controller: App\Controller\CourseController::edit

course_show:
    path: /course/courses
    controller: App\Controller\CourseController::showCourse
get_certificate:
    path: '/certificate/{id}'
    controller: 'App\Controller\CertificateController::getCertificate'
certificate_create:
    path: /certificate/create/{courseId}
    controller: App\Controller\CertificateController::create
coursedetails:
    path: '/course/{id}'
    controller: App\Controller\CourseController::courseDetails