#index:
#    path: /
#    controller: App\Controller\DefaultController::index
destination_new:
    path: /destination/new
    controller: App\Controller\DestinationController::new

comment_new:
    path: /comment/new
    controller: App\Controller\CommentController::new

destination_show:
    path: /destination/destinations
    controller: App\Controller\DestinationController::showDest

reservation_create:
    path: /reservation/create/{destinationId}
    controller: App\Controller\ReservationController::create









